"""Tests for setup.py, the script that generates per-project AI tool configs.

It had none. Two things here are worth pinning: `clean` still has to remove
what the retired Gemini target left on disk, and the generated AGENTS.md has
to keep carrying the rules that had drifted into it by hand.
"""
import importlib.util
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture(scope="module")
def setup_mod():
    """Import setup.py by path — it lives at the repo root, not in a package."""
    spec = importlib.util.spec_from_file_location("fk_setup", REPO_ROOT / "setup.py")
    mod = importlib.util.module_from_spec(spec)
    sys.modules["fk_setup"] = mod
    spec.loader.exec_module(mod)
    yield mod
    sys.modules.pop("fk_setup", None)


@pytest.fixture
def sandbox(setup_mod, monkeypatch, tmp_path):
    """Repoint every path constant at a throwaway tree."""
    monkeypatch.setattr(setup_mod, "ROOT", tmp_path)
    monkeypatch.setattr(setup_mod, "SKILLS_DIR", tmp_path / "skills")
    monkeypatch.setattr(setup_mod, "CLAUDE_COMMANDS_DIR", tmp_path / ".claude" / "commands")
    monkeypatch.setattr(setup_mod, "AGENTS_MD", tmp_path / "AGENTS.md")
    monkeypatch.setattr(setup_mod, "STATE_FILE", tmp_path / ".fk-setup.json")
    monkeypatch.setattr(
        setup_mod, "LEGACY_GEMINI_COMMANDS_DIR", tmp_path / ".gemini" / "commands" / "fk")
    monkeypatch.setattr(setup_mod, "LEGACY_GEMINI_MD", tmp_path / "GEMINI.md")
    (tmp_path / "skills").mkdir()
    (tmp_path / "skills" / "fk-demo.md").write_text("# fk-demo — A demo skill\n")
    return tmp_path


# ── the retired Gemini target ─────────────────────────────────


class TestRetiredGeminiTarget:
    def test_gemini_is_not_a_generator_any_more(self, setup_mod):
        assert "gemini" not in setup_mod.TOOLS
        assert set(setup_mod.TOOLS) == {"claude", "codex"}
        assert not hasattr(setup_mod, "generate_gemini")
        assert not hasattr(setup_mod, "generate_gemini_md")

    def test_a_stale_state_file_naming_gemini_does_not_crash_sync(
        self, setup_mod, sandbox, capsys
    ):
        """`.fk-setup.json` written before v1.3.1 records "gemini". A sync that
        raised on it would strand the user with no way to regenerate the
        targets that do still exist."""
        skills = setup_mod.discover_skills()
        setup_mod.run_generators(["claude", "gemini", "codex"], skills)

        out = capsys.readouterr().out
        assert "Skipping 'gemini'" in out
        assert "setup.py clean" in out          # and says how to tidy up
        assert (sandbox / "AGENTS.md").exists()  # the live targets still ran
        assert list((sandbox / ".claude" / "commands").glob("fk-*.md"))

    def test_clean_removes_what_the_gemini_target_left_behind(self, setup_mod, sandbox):
        """Nothing writes these any more, so `clean` is the only thing that
        will ever take them away from an install made before v1.3.1."""
        legacy_dir = sandbox / ".gemini" / "commands" / "fk"
        legacy_dir.mkdir(parents=True)
        (legacy_dir / "demo.toml").write_text('description = "x"\n')
        (sandbox / "GEMINI.md").write_text(
            "<!-- AUTO-GENERATED by setup.py — do not edit. Source: skills/ -->\n# old\n")

        setup_mod.do_clean()

        assert not (legacy_dir / "demo.toml").exists()
        assert not (sandbox / "GEMINI.md").exists()
        assert not (sandbox / ".gemini").exists()  # the empty tree goes too

    def test_clean_leaves_a_hand_written_instruction_file_alone(self, setup_mod, sandbox):
        """`clean` keys off the generated header. A file someone wrote
        themselves must survive it."""
        (sandbox / "GEMINI.md").write_text("# My own notes, not generated\n")
        (sandbox / "AGENTS.md").write_text("# Hand-written\n")

        setup_mod.do_clean()

        assert (sandbox / "GEMINI.md").exists()
        assert (sandbox / "AGENTS.md").exists()


# ── AGENTS.md is generated, and must stay lossless ────────────


class TestGeneratedAgentsMdIsComplete:
    """AGENTS.md says "do not edit" and was edited anyway: rules 14-16 and
    pipeline steps 0 and 7.5 existed only in the committed artifact, so a
    `sync` would have silently deleted three operational rules. They live in
    setup.py now — these pin them there.
    """

    @pytest.fixture
    def generated(self, setup_mod, sandbox):
        setup_mod.generate_codex(setup_mod.discover_skills())
        return (sandbox / "AGENTS.md").read_text()

    @pytest.mark.parametrize("marker", [
        "14. **Fact-check before scripting**",
        "15. **Real-people bypass**",
        "16. **Review before upscale**",
    ])
    def test_the_hand_added_rules_survive_regeneration(self, generated, marker):
        assert marker in generated

    @pytest.mark.parametrize("marker", ["0. Research", "7.5 Review videos"])
    def test_the_hand_added_pipeline_steps_survive_regeneration(self, generated, marker):
        assert marker in generated

    def test_the_skill_table_is_built_from_the_skills_directory(self, generated):
        """The committed file had drifted to 25 skills — missing 11 that exist
        and listing one that does not. Deriving it at generation time is what
        stops that happening again."""
        assert "| `/fk-demo` |" in generated

    def test_the_generated_file_is_marked_generated(self, generated):
        assert generated.splitlines()[0].startswith("<!-- AUTO-GENERATED by setup.py")


# ── argument surface ──────────────────────────────────────────


def test_tool_choices_reject_gemini(setup_mod, monkeypatch, capsys):
    monkeypatch.setattr(sys, "argv", ["setup.py", "--tool", "gemini"])
    with pytest.raises(SystemExit) as excinfo:
        setup_mod.main()
    assert excinfo.value.code == 2
    assert "invalid choice: 'gemini'" in capsys.readouterr().err


def test_discover_skills_reads_the_first_line_as_the_description(setup_mod, sandbox):
    (sandbox / "skills" / "fk-other.md").write_text("# fk-other — Does a thing\n\nBody.\n")
    found = {s["name"]: s["description"] for s in setup_mod.discover_skills()}
    assert found["other"] == "fk-other — Does a thing"
    assert found["demo"] == "fk-demo — A demo skill"
