const {contextBridge, ipcRenderer} = require('electron');
contextBridge.exposeInMainWorld('studio', Object.freeze({
  openProjectPage: (projectId, key) => ipcRenderer.invoke('open-project-page', projectId, key),
  assemblyImport: (kind, context) => ipcRenderer.invoke('assembly-import', kind, context),
  assemblyMedia: (id, action) => ipcRenderer.invoke('assembly-media', id, action),
  srtImport: context => ipcRenderer.invoke('srt-import', context),
  srtSave: id => ipcRenderer.invoke('srt-save', id),
  whisperxImport: context => ipcRenderer.invoke('whisperx-import', context),
  whisperxSave: (id,variant='full') => ipcRenderer.invoke('whisperx-save', id, variant),
  backendAction: action => ipcRenderer.invoke('backend-action', action),
  elevenlabsAction: action => ipcRenderer.invoke('elevenlabs-action', action),
  elevenlabsAudio: (id, index, action) => ipcRenderer.invoke('elevenlabs-audio', id, index, action),
  elevenlabsExport: id => ipcRenderer.invoke('elevenlabs-export', id),
  saveChatResults: ids => ipcRenderer.invoke('save-chat-results',ids),
  chatgptAction: action => ipcRenderer.invoke('chatgpt-action', action),
  api: (method, path, body) => ipcRenderer.invoke('api', method, path, body),
  settings: () => ipcRenderer.invoke('settings'),
  updateSettings: change => ipcRenderer.invoke('update-settings', change),
  chooseOutput: () => ipcRenderer.invoke('choose-output'),
  importVoice: (name, text, consent) => ipcRenderer.invoke('import-voice', name, text, consent),
  exportJob: id => ipcRenderer.invoke('export-job', id),
  preview: (id, index) => ipcRenderer.invoke('preview', id, index),
  openOutput: () => ipcRenderer.invoke('open-output'),
  openFlow: () => ipcRenderer.invoke('open-flow'),
  openExtension: () => ipcRenderer.invoke('open-extension'),
  importScriptSource: kind => ipcRenderer.invoke('import-script-source', kind),
  importScriptAudio: videoId => ipcRenderer.invoke('import-script-audio', videoId),
  importPrompts: () => ipcRenderer.invoke('import-prompts')
}));
